server:
  port: 8190

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/black_hole_station?useUnicode=true&characterEncoding=utf8&useSSL=false
    hikari:
      username: example
      password: example
      minimum-idle: 3
      maximum-pool-size: 10

  redis:
    host: 127.0.0.1
    port: 6379

aliyun:
  oss:
    access-key: LTAI1A2B3C4D5E6F
    access-secret: 1A2B3C4D5E6F7G8H9I0J
    end-point: https://oss-cn-example.aliyuncs.com
    bucket-name: example
    url-prefix: https://pic.example.com/
    namespace: black_hole_station/

mybatis:
  mapper-locations: classpath:mapper/*.xml